### PR TITLE
Un-forks Shortcode module

### LINKED ISSUE #36: Un-Fork Shortcodes
We had forked the shortcodes contrib module to get D10 and CK5 compatibility.  Looks like the default contrib module has this in version 2.0.2 now.  We should be able to remove the references to shortcode_fork and install drupal/shortcode now.

### PR DESCRIPTION
**Pull request by timurtripp**
Resolves CuBoulder/tiamat10-project-template#36

### CODE REVIEW

**Comment by timurtripp** [comment]
I'm now getting an error when I try to do this.

```
Drupal\Component\Plugin\Exception\PluginException: Plugin (shortcode) instance class "Drupal\shortcode\Plugin\Filter\Shortcode" does not exist. in Drupal\Component\Plugin\Factory\DefaultFactory::getPluginClass() (line 97 of /app/web/core/lib/Drupal/Component/Plugin/Factory/DefaultFactory.php).
```

**Comment by timurtripp** [comment]
In addition to warnings about something still trying to reference the old `shortcode_fork` path. This is after I removed the Shortcode dependency from WYSIWYG, uninstalled the fork module, cleared the caches, and then enabled the non-fork module, so I'm not sure where this can even come from.
```
include(): Failed opening '/app/web/modules/custom/shortcode_fork/src/Plugin/Filter/Shortcode.php' for inclusion (include_path='/app/vendor/pear/archive_tar:/app/vendor/pear/console_getopt:/app/vendor/pear/pear-core-minimal/src:/app/vendor/pear/pear_exception:.:/usr/local/lib/php') in include() (line 576 of /app/vendor/composer/ClassLoader.php)
include(/app/web/modules/custom/shortcode_fork/src/Plugin/Filter/Shortcode.php): Failed to open stream: No such file or directory in include() (line 576 of /app/vendor/composer/ClassLoader.php)
```

**Comment by timurtripp** [comment]
For clean installs the unfork works fine, but for the existing sandboxes I'm weary of doing this. Too many serious issues I've run into, first the deletion of all the body fields on my site and now an error that affects the entire site.

**Comment by timurtripp** [comment]
Well I was wrong, it's doing this even on a clean install now

**Review by patrickbrown-io — APPROVED** [review]
Works as advertised

**Pull request merged**
